"""Add Subscriptions and Lessons model

Revision ID: 29dbe579efe2
Revises: d626474023cc
Create Date: 2025-06-14 13:30:51.019343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dbe579efe2'
down_revision = 'd626474023cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subscriptions',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('in_archive', sa.Boolean(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['Students.user_id'], name=op.f('fk_Subscriptions_student_id_Students')),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.user_id'], name=op.f('fk_Subscriptions_teacher_id_Teachers')),
    sa.PrimaryKeyConstraint('subscription_id', name=op.f('pk_Subscriptions'))
    )
    op.create_table('Lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lesson_date_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled_in_time', 'missed', name='lesson_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('online_call_url', sa.String(length=255), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['Students.user_id'], name=op.f('fk_Lessons_student_id_Students')),
    sa.ForeignKeyConstraint(['subscription_id'], ['Subscriptions.subscription_id'], name=op.f('fk_Lessons_subscription_id_Subscriptions')),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.user_id'], name=op.f('fk_Lessons_teacher_id_Teachers')),
    sa.PrimaryKeyConstraint('lesson_id', name=op.f('pk_Lessons'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lessons')
    op.drop_table('Subscriptions')
    # ### end Alembic commands ###
