"""Add Discipline and TeacherDisciplineAssociation models

Revision ID: 62ab029df94f
Revises: 29dbe579efe2
Create Date: 2025-06-14 21:31:47.494462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ab029df94f'
down_revision = '29dbe579efe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Disciplines',
    sa.Column('discipline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['Administrators.Users_user_id'], name=op.f('fk_Disciplines_administrator_id_Administrators')),
    sa.PrimaryKeyConstraint('discipline_id', name=op.f('pk_Disciplines'))
    )
    op.create_table('Teachers_has_Disciplines',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['Disciplines.discipline_id'], name=op.f('fk_Teachers_has_Disciplines_discipline_id_Disciplines')),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.user_id'], name=op.f('fk_Teachers_has_Disciplines_teacher_id_Teachers')),
    sa.PrimaryKeyConstraint('teacher_id', 'discipline_id', name=op.f('pk_Teachers_has_Disciplines'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teachers_has_Disciplines')
    op.drop_table('Disciplines')
    # ### end Alembic commands ###
