"""Create Tests models

Revision ID: 664e97f3529c
Revises: a7339b82daef
Create Date: 2025-06-17 10:10:30.925483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664e97f3529c'
down_revision = 'a7339b82daef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tests',
    sa.Column('test_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('complexity', sa.Enum('easy', 'medium', 'difficult', name='complexity_enum'), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['Disciplines.discipline_id'], name=op.f('fk_Tests_discipline_id_Disciplines')),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.user_id'], name=op.f('fk_Tests_teacher_id_Teachers')),
    sa.PrimaryKeyConstraint('test_id', name=op.f('pk_Tests'))
    )
    op.create_table('Tests_has_Education_exerсizes',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('purpose_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['Education_exerсizes.exercise_id'], name=op.f('fk_Tests_has_Education_exerсizes_exercise_id_Education_exerсizes')),
    sa.ForeignKeyConstraint(['test_id'], ['Tests.test_id'], name=op.f('fk_Tests_has_Education_exerсizes_test_id_Tests')),
    sa.PrimaryKeyConstraint('test_id', 'exercise_id', name=op.f('pk_Tests_has_Education_exerсizes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tests_has_Education_exerсizes')
    op.drop_table('Tests')
    # ### end Alembic commands ###
