"""Initial migration

Revision ID: 6d8923093daf
Revises: 
Create Date: 2025-05-20 17:32:47.667618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8923093daf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_enum'), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=255), nullable=True),
    sa.Column('unique_code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_Users')),
    sa.UniqueConstraint('email', name=op.f('uq_Users_email')),
    sa.UniqueConstraint('unique_code', name=op.f('uq_Users_unique_code'))
    )
    op.create_table('Administrators',
    sa.Column('Users_user_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Enum('logs', 'full', name='access_level_enum'), nullable=True),
    sa.ForeignKeyConstraint(['Users_user_id'], ['Users.user_id'], name=op.f('fk_Administrators_Users_user_id_Users')),
    sa.PrimaryKeyConstraint('Users_user_id', name=op.f('pk_Administrators'))
    )
    op.create_table('Parents',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_name', sa.String(length=100), nullable=True),
    sa.Column('work_phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name=op.f('fk_Parents_user_id_Users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_Parents'))
    )
    op.create_table('Students',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name=op.f('fk_Students_user_id_Users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_Students'))
    )
    op.create_table('Teachers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('main_work', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name=op.f('fk_Teachers_user_id_Users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_Teachers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teachers')
    op.drop_table('Students')
    op.drop_table('Parents')
    op.drop_table('Administrators')
    op.drop_table('Users')
    # ### end Alembic commands ###
