"""Correcting Lesson Model

Revision ID: 8df93e9f419b
Revises: 9e11f28e4f89
Create Date: 2025-06-15 14:20:28.474621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df93e9f419b'
down_revision = '9e11f28e4f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Lessons_discipline_id_Disciplines'), 'Disciplines', ['discipline_id'], ['discipline_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Lessons_discipline_id_Disciplines'), type_='foreignkey')
        batch_op.drop_column('discipline_id')

    # ### end Alembic commands ###
