"""Correcting models

Revision ID: 9e11f28e4f89
Revises: b932b00310f4
Create Date: 2025-06-15 14:07:07.315235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e11f28e4f89'
down_revision = 'b932b00310f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Lessons_classroom_id_Classrooms'), 'Classrooms', ['classroom_id'], ['classroom_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Lessons_classroom_id_Classrooms'), type_='foreignkey')
        batch_op.drop_column('classroom_id')

    # ### end Alembic commands ###
