"""Create EducationClassifier, EducationModule, EducationExercise models

Revision ID: a7339b82daef
Revises: 8df93e9f419b
Create Date: 2025-06-16 11:57:02.626148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7339b82daef'
down_revision = '8df93e9f419b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Education_classifier',
    sa.Column('classifier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['Administrators.Users_user_id'], name=op.f('fk_Education_classifier_administrator_id_Administrators')),
    sa.ForeignKeyConstraint(['discipline_id'], ['Disciplines.discipline_id'], name=op.f('fk_Education_classifier_discipline_id_Disciplines')),
    sa.PrimaryKeyConstraint('classifier_id', name=op.f('pk_Education_classifier'))
    )
    op.create_table('Education_modules',
    sa.Column('module_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('preview_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('classifier_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classifier_id'], ['Education_classifier.classifier_id'], name=op.f('fk_Education_modules_classifier_id_Education_classifier')),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.user_id'], name=op.f('fk_Education_modules_teacher_id_Teachers')),
    sa.PrimaryKeyConstraint('module_id', name=op.f('pk_Education_modules'))
    )
    op.create_table('Education_exerсizes',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('verification_type', sa.Enum('auto', 'manual', name='verification_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('right_answer', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['Education_modules.module_id'], name=op.f('fk_Education_exerсizes_module_id_Education_modules')),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.user_id'], name=op.f('fk_Education_exerсizes_teacher_id_Teachers')),
    sa.PrimaryKeyConstraint('exercise_id', name=op.f('pk_Education_exerсizes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Education_exerсizes')
    op.drop_table('Education_modules')
    op.drop_table('Education_classifier')
    # ### end Alembic commands ###
