"""Add Branch and Classroom models

Revision ID: b932b00310f4
Revises: 62ab029df94f
Create Date: 2025-06-14 21:45:42.595020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b932b00310f4'
down_revision = '62ab029df94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Branches',
    sa.Column('branch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('working_start', sa.Time(), nullable=False),
    sa.Column('working_end', sa.Time(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['Administrators.Users_user_id'], name=op.f('fk_Branches_administrator_id_Administrators')),
    sa.PrimaryKeyConstraint('branch_id', name=op.f('pk_Branches'))
    )
    op.create_table('Classrooms',
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['Administrators.Users_user_id'], name=op.f('fk_Classrooms_administrator_id_Administrators')),
    sa.ForeignKeyConstraint(['branch_id'], ['Branches.branch_id'], name=op.f('fk_Classrooms_branch_id_Branches')),
    sa.PrimaryKeyConstraint('classroom_id', name=op.f('pk_Classrooms'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Classrooms')
    op.drop_table('Branches')
    # ### end Alembic commands ###
