"""Create Active tests models

Revision ID: bffe70d2cccc
Revises: 664e97f3529c
Create Date: 2025-06-17 13:28:44.674052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffe70d2cccc'
down_revision = '664e97f3529c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Active_tests',
    sa.Column('active_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active_sent', 'active_not_sent', name='active_test_status'), nullable=False),
    sa.Column('assessment', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lessons.lesson_id'], name=op.f('fk_Active_tests_lesson_id_Lessons')),
    sa.ForeignKeyConstraint(['student_id'], ['Students.user_id'], name=op.f('fk_Active_tests_student_id_Students')),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.user_id'], name=op.f('fk_Active_tests_teacher_id_Teachers')),
    sa.ForeignKeyConstraint(['test_id'], ['Tests.test_id'], name=op.f('fk_Active_tests_test_id_Tests')),
    sa.PrimaryKeyConstraint('active_id', name=op.f('pk_Active_tests'))
    )
    op.create_table('Tests_packages',
    sa.Column('package_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_verification', sa.Enum('verified', 'not_verified', name='verification_status'), nullable=False),
    sa.Column('exercise_start', sa.DateTime(), nullable=True),
    sa.Column('exercise_end', sa.DateTime(), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('accumulated_score', sa.Integer(), nullable=True),
    sa.Column('active_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_id'], ['Active_tests.active_id'], name=op.f('fk_Tests_packages_active_id_Active_tests')),
    sa.ForeignKeyConstraint(['exercise_id'], ['Education_exerсizes.exercise_id'], name=op.f('fk_Tests_packages_exercise_id_Education_exerсizes')),
    sa.PrimaryKeyConstraint('package_id', name=op.f('pk_Tests_packages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tests_packages')
    op.drop_table('Active_tests')
    # ### end Alembic commands ###
